title: Open the Settings View.
level: 4
ref: open-settings
content: |

    .. list-table::
       :header-rows: 1
   
       * - Operating System
         - Methods

       * - MacOS
         - .. list-table::
              :header-rows: 1

              * - Method
                - Action

              * - Visual Studio Code Menu
                - :guilabel:`Code` > 
                  :guilabel:`Preferences` > 
                  :guilabel:`Settings`

              * - Keyboard Shortcut
                - Press ``Command`` + ``,``

       * - Windows and Linux
         - .. list-table::
              :header-rows: 1

              * - Method
                - Action

              * - Visual Studio Code Menu
                - :guilabel:`File` > 
                  :guilabel:`Preferences` > 
                  :guilabel:`Settings`

              * - Keyboard Shortcut
                - Press ``Ctrl`` + ``,``

---
title: Search "MongoDB" in the :guilabel:`Settings` search bar.
level: 4
ref: search-mongodb-in-settings
content: |
    |vsce| extension settings are displayed. Changes you 
    make are saved automatically.
...
